### ISSUE TITLE
Git repo content not matching AWS web site

### ISSUE THREAD

**Issue by pcolmer** [awsdocs/amazon-ses-developer-guide#10]
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html is missing everything in https://github.com/awsdocs/amazon-ses-developer-guide/blob/master/doc-source/smtp-credentials.md from "Obtaining Amazon SES SMTP Credentials by Converting AWS Credentials" onwards.

This is really important information and I am bemused that (somehow) it is no longer appearing on the public web site. The information *used* to be there …

**Comment by toretore** [comment]
It seems that the web site is using version 4 while in the source it's still using version 2. They both worked when I tried them (version is prepended to signature before base64-ing).

**Comment by BrentAtAWS** [comment]
This issue has been resolved. The Github repo was well out of sync with the official documentation.
