### ISSUE TITLE
Seemingly incorrect example of an authorization policy condition check

### ISSUE THREAD

**Issue by copumpkin** [awsdocs/amazon-ses-developer-guide#11]
In [this page](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/sending-authorization-policies.html), the following snippet of IAM is recommended:

```json
"Condition": {
    "StringLike": {
      "ses:FromAddress": "invoicing+.*@example.com"
    }
}
```

Which is described in text as specifying "that the delegate sender can only send from a "From" address that starts with invoicing and ends with example.com".

Unless `StringLike` behaves very differently on SES policies than elsewhere, it seems like the correct translation of that description wouldn't include the `+.` characters, so it's a bit unclear.

**Comment by BrentAtAWS** [comment]
My apologies--I fixed this issue a long time ago, but never closed out this issue. Thanks for pointing this out!
