### ISSUE TITLE
Seemingly incorrect description of IAM policy behavior

### ISSUE THREAD

**Issue by copumpkin** [awsdocs/amazon-ses-developer-guide#12]
In the documentation page on [sending authorization policies](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/sending-authorization-policies.html), the policy evaluation behavior is described as follows:

> Each statement includes the core information about a single permission. If a policy includes multiple statements, Amazon SES applies a logical OR across the statements at evaluation time. Similarly, if an identity has multiple policies attached to it, Amazon SES applies a logical OR across the policies at evaluation time.

This doesn't seem correct based on IAM behavior elsewhere and a couple of experiments I ran, and could lead to user confusion. In general, in IAM, statements aren't simply ORed together because `Deny` statements win over any `Allow` statements, so the more correct way to describe the overall behavior of a policy is to OR the allows together AND NOT any of the deny statements, or something like this. It seems simpler to refer people back to the central IAM evaluation behavior documentation, however, than to try to explain it again.

More confusing for me was the "logical OR across the policies at evaluation time", which suggested that the policies were considered in isolation and the evaluation results ORed together. The distinction would be if I had an identity policy containing only a matching `Allow`, and another containing only a matching `Deny`, would the two interfere with one another? Logically ORing the two policy evaluations means the `Allow` would grant me access, but "stacking" the policies (as is more common in the IAM world), I'd be thwarted by the `Deny`. I experimented a bit and the stacking behavior seems to be what actually happens, so it's not really a logical OR across the policies.

Can this page be clarified a bit?

**Comment by copumpkin** [comment]
cc @BrentAtAWS @coltoncat @jschwarzwalder since I'm not sure who on the SES team is active on this issue tracker and haven't seen any engagement from AWS on prior issues submitted here. Pinging those of you who appear to be at AWS and have engaged on PRs in the past 😄

**Comment by jschwarzwalder** [comment]
Thank you for reaching out. 

I will share this message with the writer for this service.

We appreciate your feedback.

**Comment by copumpkin** [comment]
@jschwarzwalder thanks! Also note that I filed a couple of other closely related issues (#11, #13) about confusing/misleading documentation on SES authorization policies

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
