### ISSUE TITLE
Confusing description of domain/email identity policy behavior

### ISSUE THREAD

**Issue by copumpkin** [awsdocs/amazon-ses-developer-guide#13]
In [this documentation page](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/sending-authorization-identity-owner-tasks-policy.html), there's the following snippet:

> Policies attached to email address identities override policies attached to the corresponding domain identities. For example, say that you have verified example.com and user@example.com. If you create a policy for example.com that disallows a delegate sender, and you create a policy for user@example.com that allows that delegate sender, the delegate sender will be able to send from user@example.com if they specify the ARN of user@example.com in the request to send the email.

The use of the word _override_ there was confusing to me, because it makes it sound like the email identity policy wins over the corresponding domain identity policy. But if I have this scenario:

1. Domain identity policy for `example.com` allows `ses:SendEmail`
2. Email identity policy for `copumpkin@example.com` has an explicit `Deny` for any calls to `ses:SendEmail`

Now, if someone invokes `SendEmail` with a `SourceArn` of `identity/example.com` with a sender of `copumpkin@example.com`, only the domain identity policy seems to apply, because that's the policy attached to the `SourceArn` specified.

In many ways, that makes sense, and has less "non-local" behavior than the behavior implied by the documentation today. It seems more correct and succinct to say that the policies attached to the `SourceArn` specified are the only ones that will apply, so if you specify the domain ARN, you get the domain's identity policies. If you specify the email's ARN, you get the email's identity policies. And there's no (as far as I've been able to observe) interaction between the two.

Have I misunderstood the behavior?

**Comment by amberkushwaha** [comment]
if you will make an example for deleteerge.com,the example will get reimburse in the same issue back again,so in future issues do notify the same with the deleteerge "issues"

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
