### ISSUE TITLE
Seemingly incorrect description of SES Bounce rate in documentation

### ISSUE THREAD

**Issue by wolruf** [awsdocs/amazon-ses-developer-guide#17]
I believe there's a small issue in the documentation, would definitely like feedback.

URI:
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/monitor-sending-activity.html 
shows Console SES "calculated rate" for "Bounce and complaint rates"
though Amazon CloudWatch console shows "count only" for "bounces, complaints"

The Cloudwatch should be "calculated rate" for bounces and complaints, as described in this other page:
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/reputationdashboard-cloudwatch-alarm.html

**Comment by BrentAtAWS** [comment]
CloudWatch actually shows both the numbers of bounces and complaints, as well as the calculated bounce and complaint rates. I'll clarify this point in the documentation.
