### ISSUE TITLE
Confusing describe-configuration-set command example

### ISSUE THREAD

**Issue by chausme** [awsdocs/amazon-ses-developer-guide#19]
Seems an example `aws ses describe-configuration-set --configuration-set-name ConfigSet --region us-west-2` command at https://docs.aws.amazon.com/ses/latest/DeveloperGuide/monitoring-sender-reputation-pausing-configuration-set.html#monitoring-sender-reputation-pausing-configuration-set-part-4 doesn't return ReputationOptions for a configuration set which is potentially confusing

Likely it should be replaced with `aws ses describe-configuration-set --configuration-set-name ConfigSet --configuration-set-attribute-names reputationOptions --region us-west-2`

**Comment by BrentAtAWS** [comment]
Thanks for pointing this out. I'll update the documentation to clarify this point. Thanks!
