### ISSUE TITLE
Improve SNS Lambda event example

### ISSUE THREAD

**Issue by farski** [awsdocs/amazon-ses-developer-guide#23]
The [Sample Incoming Email Event](https://github.com/awsdocs/amazon-ses-developer-guide/blob/master/doc-source/receiving-email-action-lambda-event.md) doesn't make any mention of the fact that with events provided by the SNS action, the `Message` attribute will contain JSON-encoded data (i.e., a string). In fact, the way it presents the example event and example message, it looks like the message will be an object.

I realize this is true of _all_ SNS event messages, but it would be helpful if the docs explicitly stated that the `Message` attribute were a string of JSON that needs to be decoded.

**Comment by BrentAtAWS** [comment]
Thanks for your suggestion. I'll add some clarifying information to the documentation.
