### ISSUE TITLE
Using custom verification email templates > missing information about the positioning of the verification link 

### ISSUE THREAD

**Issue by i5heu** [awsdocs/amazon-ses-developer-guide#27]
On [Q10](https://github.com/awsdocs/amazon-ses-developer-guide/blob/master/doc-source/send-email-verify-address-custom.md#q10-can-i-remove-the-text-that-appears-at-the-bottom-of-custom-verification-emails):
>The following text is automatically added to the end of every custom verification email and cannot be removed:
>
>*If you did not request to verify this email address, please disregard this message. If you have any concerns, please forward this message to the following email address along with your questions or comments. *
>
>The email address link in this text refers to aws-email-domain-verification@amazon.com, an inbox that is actively monitored by the Amazon SES team.

It is not described how to set the position of the verification link, which is movable after Q10 and also added to the end of every custom verification email.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
