### ISSUE TITLE
Syntax error on Python script?

### ISSUE THREAD

**Issue by purdy** [awsdocs/amazon-ses-developer-guide#40]
I'm trying to use the Python script on [the guide page](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html#python) and running into a syntax error:

```
$ python3 ./smtp_creds.py wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY us-east-1
  File "./smtp_creds.py", line 39
    raise ValueError(f"The {region} Region doesn't have an SMTP endpoint.")
                                                                         ^
SyntaxError: invalid syntax
```

**Comment by yunpengeric** [comment]
Hi Purdy,

What version of python are you using? 
When I used python 2.7, I could replicate the error.
```
python ./smtp_creds.py wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY us-east-1
  File "./smtp_creds.py", line 39
    raise ValueError(f"The {region} Region doesn't have an SMTP endpoint.")
                                                                         ^
SyntaxError: invalid syntax
```
But when I used python 3.6 and 3.7, it was working.
```
python3 ./smtp_creds.py wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY us-east-1
BLBM/9hSUELfq8Gw+rU1YcBjkOxGbhT2XG763xVLGWL9
```

**Comment by purdy** [comment]
That was it ... I was using a default python on my computer, which was v2. v3 works.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
