### ISSUE TITLE
Why is the inner message "11111111" called DATE in the (pseudo)code?

### ISSUE THREAD

**Issue by jrhunger** [awsdocs/amazon-ses-developer-guide#41]
Wouldn't it be less confusing to call it something like SEED or SEEDMSG?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
