### ISSUE TITLE
Capitalization of Troubleshoot Amazon SES issues > notification problems

### ISSUE THREAD

**Issue by kshammer** [awsdocs/amazon-ses-developer-guide#48]
Hello, 

There is a small capitalization issue on the side bar of the documentation. 

![image](https://user-images.githubusercontent.com/5688067/115291192-4c312980-a109-11eb-8613-cd5dee8b1a18.png)

I attempted to find the issue within the md documents but I was unable to find it.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
