### ISSUE TITLE
Missing instructions on how to create a distribution from scratch.

### ISSUE THREAD

**Issue by vjleo** [awsdocs/amazon-ses-developer-guide#54]
"If you use Amazon CloudFront as your CDN, complete the following procedures:

    On the CloudFront Distributions page, choose the distribution that corresponds with your CDN.

    On the Behaviors tab, choose the default behavior, and then choose Edit.

    For Cache Based on Selected Request Headers, choose All.

    For Query String Forwarding and Caching, choose Forward all, cache based on all.
"

What should be the origin?
Tried creating a new s3 bucket to use as origin but the " For Cache Based on Selected Request Headers, choose All." cant be applied to buckets with s3 origin.

This is the document:
https://github.com/awsdocs/amazon-ses-developer-guide/blob/master/doc-source/configure-custom-open-click-domains.md

**Comment by amberkushwaha** [comment]
"If you use Amazon CloudFront as your CDN, complete the following procedures:

On the CloudFront Distributions page, choose the distribution that corresponds with your CDN.

On the Behaviors tab, choose the default behavior, and then choose Edit.

For Cache Based on Selected Request Headers, choose All.

For Query String Forwarding and Caching, choose Forward all, cache based on all.
"

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
