### ISSUE TITLE
Please add Java example for ses_VerifyEmailIdentity_section.md

### ISSUE THREAD

**Issue by ilentt** [awsdocs/amazon-ses-developer-guide#59]
https://github.com/awsdocs/amazon-ses-developer-guide/blob/master/doc-source/example_ses_VerifyEmailIdentity_section.md

Current only have python example, please add Java example

**Comment by amberkushwaha** [comment]
java has been updated to this link.

**Comment by amberkushwaha** [comment]
_**### currently only have python example, please add java example

https://github.com/awsdocs/amazon-ses-developer-guide/blob/master/doc-source/example_ses_verifyemailidentity_section.md.
java has been updated to this link.**_

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
