### ISSUE TITLE
Maximum sending rate exceeded

### ISSUE THREAD

**Issue by umerghori786** [awsdocs/amazon-ses-developer-guide#60]
Hi i am using aws ses for emails but when i sent 200 emails it sent only 90 email and remaining email not sent.. it show this error
exception 'Aws\Ses\Exception\SesException' with message 'Error executing "SendEmail" on "https://email.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://email.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response:
<ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
  <Error>
    <Type>Sender</Type>
    <Code>Throttling< (truncated...)
 Throttling (client): Maximum sending rate exceeded. - <ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
  <Error>
    <Type>Sender</Type>
    <Code>Throttling</Code>
    <Message>Maximum sending rate exceeded.</Message>
  </Error>
  <RequestId>8f23e6e6-b4f2-4572-b426-343b370cb32c</RequestId>
</ErrorResponse>

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
