### ISSUE TITLE
Unable to send and receive email with attachment when called from AWS Lambda

### ISSUE THREAD

**Issue by sachinmittal2212** [awsdocs/amazon-ses-developer-guide#62]
Below code is not showing any error when run, but it is still not sending/receiving email with attachment:
   
    import email
    from email.mime.multipart import MIMEMultipart
    from email.mime.text import MIMEText
    from email import header
    from email.mime.application import MIMEApplication
    
    def email_from_S3(self,S3,senderFile):
            print('Sending Email...')
            Sender = 'Sachin.Mittal@invesco.com'
            Recipient ='sachinmittal2212@gmail.com'
            Attachment = 'C:/Users/mittas1/Downloads/'+senderFile
            S3.s3_client.download_file(S3.bucket,'output/'+senderFile,Attachment)
            msg = MIMEMultipart()   
            msg['Subject'] = 'CRD_Extract'
            msg['From'] =  Sender
            msg['To'] = Recipient
            textpart = MIMEText('The output file was downloaded from S3')
            msg.attach(textpart)
            att = MIMEApplication(open(Attachment, 'rb').read())
            att.add_header('Content-Disposition','attachment',filename=Attachment)
            msg.attach(att)
            try:
                response = S3.ses_client.send_raw_email(
                Source=Sender,
                Destinations=[Recipient],
                RawMessage={"Data":msg.as_string()}
            )
            except ClientError as e:
                print(e.response['Error']['Message'])
            else:
                print("Email sent! Message ID:",response['MessageId'])

**Comment by amberkushwaha** [comment]
response been updated and issue has been resolved as per the guidelines,

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
