### ISSUE TITLE
Please add note on S3 bucket regions.

### ISSUE THREAD

**Issue by kazu23pole** [awsdocs/amazon-ses-developer-guide#63]
When adding a batch to the suppression list, the S3 region where the list of addresses is uploaded must be the same as the SES region, or an error will occur.

Please add this note as it is not included in the documentation.

https://github.com/awsdocs/amazon-ses-developer-guide/blob/master/doc-source/sending-email-suppression-list.md?plain=1#L175

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
