### ISSUE TITLE
"Warning" reputation metric status not documented

### ISSUE THREAD

**Issue by Hopper262** [awsdocs/amazon-ses-developer-guide#64]
On the guide pages [Using reputation metrics](https://docs.aws.amazon.com/ses/latest/dg/reputation-dashboard-dg.html) and [Reputation metrics messages](https://docs.aws.amazon.com/ses/latest/dg/reputationdashboardmessages.html), several status values are listed for the Bounce and Complaint rate sections, but one of my metrics pages displays "Warning"  for the complaint rate, a value which is not on the documented list.

While I'm not confused about what "Warning" is telling me, it'd be nice to see the documentation in sync with the values possible in the current dashboard code. I'm not sure if "Warning" replaced "Almost healed" or "Under review," for instance. Thanks in advance for considering this!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
