### ISSUE TITLE
BYODKIM documentation does not specify PKCS#1 which breaks on OpenSSL 3.0 or later

### ISSUE THREAD

**Issue by nonspecialist** [awsdocs/amazon-ses-developer-guide#71]
Nowhere in this documentation does it mention that BYODKIM requires a PKCS#1 formatted private key.

I've just lost a day fighting with this because OpenSSL after 3.0 (which was released in 2021) generates PKCS#8 RSA keys by default.

The SES console silently accepts them (because we are forced to strip off the header and footer and reformat the key material without whitespace -- which is also dumb) and happily creates the sending identity which then NEVER VALIDATES.

It would be very helpful if this guide could mention that users of OpenSSL from 3.0 onwards need to provide the `-traditional` flag when generating the key to get a PKCS#1 private key

For example:

```
$ openssl genrsa -f4 -traditional -out private-key.pem 2048
```

**Comment by JABirchall** [comment]
I had the same issue issue. Wasted a week, trying to figure out why SES wasnt verifing our domain only recently found that we had to add -traditional to key generation and it was verified within 5 minutes. 

Would be nice if AWS either updated docs to show this OR accept newer PKCS#8 keys. 

Any reason why AWS is forcing us to use a key mechanisism that OpenSSL dropped support for 10 years ago?

**Comment by amberkushwaha** [comment]
AWS and SES files been updated at prior,also the PKCS issue also have been resolved.dropped support for 10 years.and also been updated several times.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
