### ISSUE TITLE
Update Version Language for Identity Policy

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/amazon-ses-developer-guide#72]
Update Version language for Identity Policy.  Current phrasing is misleading and there are only 2 policy versions that are valid.:

**Comment by jsoncow** [comment]
https://github.com/awsdocs/amazon-ses-developer-guide/pull/73

**Comment by amberkushwaha** [comment]
the policy version in this frame has not been update since jul2022,so kindly change the version and policy heading.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
