### ISSUE TITLE
Add an example for using delegate sender with the SMTP gateway

### ISSUE THREAD

**Issue by ajoga** [awsdocs/amazon-ses-developer-guide#8]
Hello, 

Related AWS case id : 5339866351 

I pulled my hair for a long time after seeing this part of the doc : https://github.com/awsdocs/amazon-ses-developer-guide/blob/723822f311b6f310763e290a2d8c5e7d863cc9c0/doc-source/sending-authorization-delegate-sender-tasks-email.md#using-the-amazon-ses-smtp-interface 

(note that this is the only hit for "X-SES-SOURCE-ARN" in the complete documentation). 

It would be great to have an exemple on the example page so this detail don't get overlooked : https://docs.aws.amazon.com/ses/latest/DeveloperGuide/sending-authorization-policy-examples.html 

I also did the PR #7 to clear up how important this thing is ... 

Thanks

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
